# ----------------------- #
#   目录结构配置                             #
# ----------------------- #
# 默认（推荐）的目录结构如下
#(.)
# |
# +- site
# |   |
# |   +- config.yml (The site configuration file)
# |   |
# |   +- source (All YAML front-matter header files and some static files)
# |   |
# |   +- templates (FreeMarker template ONLY)
# |   |
# |   +- assets (All static files ONLY)
# |  
# +- (site2) another site
# |
# +- public
#     |
#     +- site the output directory for site
#     |
#     +- (site2) the output directory for site2
#


# 指定站点目录，默认是当前文件所在的目录。对于站点中的子目录，有以下要求（或规则）
#   source：   必须存在
#   templates：如果该目录不存在，则取目录 source/_templates。二者之一必须存在。
#   assets:    如果该目录不存在，则表示所有的静态资源都在 source目录中，并没有单独
#                分出来。分了站点生成效率，建议将静态资源分离出来放置在改目录中。
# 进行版本管理（备份）时，管理 site 这一个目录即可。
# site: site

# 站点生成的目标目录。如果在本机分布，可以是 "/var/www/html"。
# 如果不指定，默认在 site 父级目录中创建 public/site 作为该属性的值。
# destination: public/site

# 工作目录。用于生成站点时的中间过程和模板缓存等。
# 如果不指定，默认在 java 临时文件夹中创建 opoopresscache 用于工作目录。
# 参考 java 属性 java.io.tmpdir
# working_dir: target/working_dir


# ----------------------- #
#      主要配置                              #
# ----------------------- #

locale: zh_CN
url: http://opoo.org
title: Opoo.org
subtitle: 学而记之，谓之志。
author: Alex Lin
simple_search: http://google.com/search
description: 'Opoo.org 是一个专注于计算机软件、编程语言、项目管理、开源产品、互联网科技等的原创 IT 技术博客。'
keywords: 'OpooPress, 编程, 开源, java, joqs, WordPress, flex, maven, docbook, sourceforge, openshift'

# 默认的日期格式是 "ordinal"(相当于 java 日期格式的 "MMM d yyyy"，输出 "四月 15 2013")
# 可以直接指定一个 java 日期格式字符串，例如 "yyyy年MM月dd日"
date_format: "ordinal"

# RSS 订阅使用的 URL
subscribe_rss: http://opoo.org/atom.xml
subscribe_email:
# RSS feeds can list your email address if you like
email:

# 如果发布到子目录如 http://site.com/project 则设置 'root: /project'
root: /

# 固定链接支持的变量 ：
# 		post 的 front-matter 头部变量 ，以及 ${year}, ${month}, ${day}, ${hour}, ${minute}, ${second}, ${name}, ${pathToFile}, ${fileName} 
permalink: /${name}/
# permalink_label: "&infin;"
# permalink_label_feed: "&#9875; 固定链接"

# 新建文章的文件全路径（相对于 source 目录），支持变量 : {year}, ${month}, ${day}, ${hour}, ${minute}, ${second}, ${name}, ${title}, ${date}
new_post: article/${year}-${month}-${day}-${name}.markdown

# 新建页面的文件全路径（相对于 source 目录），支持变量  : ${year}, ${month}, ${day}, ${hour}, ${minute}, ${second}, ${name}, ${title}, ${date}
new_page: ${name}.markdown

# 分类所在的目录
category_dir: /category

# 分类目录名称与标题对照关系。通常名称用于组成 URL，小写切不含空格，标题则用于显示。
# 未在此处指定的分类 OpooPress 会自行处理。
category_names: {"opoopress": "OpooPress", "tech": "技术", tech.java: "Java", tech.maven: "Maven", "uncategorized": "未分类", "others":"杂项"}

# Category title prefix.
category_title_prefix: "分类: "

# 标签所在的目录
tag_dir: /tag

# 标签名称与标题对照关系。通常名称用于组成 URL，小写切不含空格，标题则用于显示。
tag_names: {"opoopress": "OpooPress", "blog": "博客", "opensource": "开源", "plugins": "插件"}

# 标签标题前缀
tag_title_prefix: "标签："

# 首页每页显示的文章数
paginate: 10          		

# 要显示的最新文章数
recent_posts: 7

# 相关文章的最大数量
related_posts: 5   	

# 在显示摘要的文章中'继续阅读'的按钮文字
excerpt_link: "继续阅读"

# 摘要在文章中的分隔标识
excerpt_separator: "<!--more-->"

# 文章或者页面的标题是否使用 titlecase
titlecase: true

# 主导航菜单
navs: {"文章": "/", "归档": "/archives/", "开源": "/opensource/", "关于": "/about/"}

# 侧边栏默认包含的模板数组。
# 被设置的模板片段应该位于  [模板路径]/asides 目录，例如 site/templates/asides 或者 site/source/_templates/asides.
default_asides: [about.ftl, recent_posts.ftl, recent_comments.ftl, github.ftl, delicious.ftl, pinboard.ftl, googleplus.ftl, categories.ftl, tags.ftl]

# 首页侧边栏包含的模板，未设置使用 default_asides
# blog_index_asides:
# 文章页面侧边栏包含的模板，未设置使用 default_asides
# post_asides:
# 普通页面侧边栏包含的模板，未设置使用 default_asides
# page_asides:

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

# Github repositories
github_user:
github_repo_count: 0
github_show_profile_link: false
github_skip_forks: true

# Twitter
twitter_user:
twitter_tweet_button: false

# Google +1
google_plus_one: false
google_plus_one_size: medium

# Google Plus Profile
# Hidden: No visible button, just add author information to search results
googleplus_user: 
googleplus_hidden: false

# Pinboard
pinboard_user: 
pinboard_count: 3

# Delicious
delicious_user: 
delicious_count: 3

# Disqus Comments
disqus_short_name: opoo
disqus_show_comment_count: true

# Google Analytics
google_analytics_tracking_id: "UA-30835382-1"
google_analytics_tracking_domain: "none"

# Facebook Like
facebook_like: false


# ----------------------- #
#   Deployment Settings   #
# ----------------------- #
# deploy_server: {id: my_vps_server, url: 'scp://my.vps.ip/var/www/html', user: 'ssh_username'}



###############################################################################
## 以下配置主要给开发人员使用，如果您不做二次开发或者不清楚各个参数的含义，
## 请勿修改以下的各个参数 
###############################################################################

# ----------------------- #
#   PlugIns Settings      #
# ----------------------- #
plugins: 
  - org.opoo.website.plugin.OpooOrgPlugin


# ------------------------ #
# Default PlugIn Settings  #
# ------------------------ #
converters:
  - org.opoo.press.converter.TxtmarkMarkdownConverter
  - org.opoo.press.converter.TextilejConverter

generators:
  - org.opoo.press.generator.PaginationGenerator
  - org.opoo.press.generator.CategoryGenerator
  - org.opoo.press.generator.TagGenerator
  
# siteFilters:
#  - org.opoo.press.filter.SampleSiteFilter

# SlugHelper
slugHelper: org.opoo.press.slug.ChineseToPinyinSlugHelper


# ----------------------- #
#   Code Block Settings   #
# ----------------------- #

# Default use 'SyntaxHighlighter' as the highlighter code block processor
# http://alexgorbatchev.com/SyntaxHighlighter/
highlighter: "org.opoo.press.highlighter.SyntaxHighlighter"


# ----------------------- #
#   FreeMarker config     #
# ----------------------- #

# auto_import_templates:{"ns" : "template_name.ftl", "ns2" : "template2_name.ftl"}
# auto_include_templates: ["global_template1.ftl", "global_template2.ftl"]


